FROM apache/airflow:2.9.2-python3.11

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libgomp1 \
    && rm -rf /var/lib/apt/lists/*

USER airflow

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

COPY pipeline/airflow/dags/ ${AIRFLOW_HOME}/dags/
COPY models/ /opt/airflow/models_src/
COPY pipeline/ /opt/airflow/pipeline/
COPY policies/ /opt/airflow/policies/

ENV PYTHONPATH=/opt/airflow
